-- MySQL Script generated by MySQL Workbench
-- Wed Oct 24 01:45:19 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema starships_table
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema starships_table
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `starships_table` DEFAULT CHARACTER SET utf8 ;
USE `starships_table` ;

-- -----------------------------------------------------
-- Table `starships_table`.`starships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `starships_table`.`starships` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `fabricante` VARCHAR(100) NOT NULL,
  `costo` FLOAT(10,2) NOT NULL,
  `longitud` FLOAT(10,2) NOT NULL,
  `velocidad` FLOAT(10,2) NOT NULL,
  `tripulacion` INT NOT NULL,
  `pasajeros` INT NOT NULL,
  `capacidad_carga` INT NOT NULL,
  `suministros` INT NOT NULL,
  `relacion_impulsor` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
